[package]
name = "oats_primitives"
version = "0.1.0"
edition = "2024"

[lib]
name = "oats_primitives"
crate-type = ["rlib", "staticlib"]

[dependencies]
libc = "0.2"
runtime = { path = "../runtime" }
